=== BackupTheBerlios/jpulsemonitor/JPulseMonitor/resources/administration.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD for administration -->
<!ELEMENT administration (configuration?, training_types*, trainings*, users*, customfields) >
<!ELEMENT trainings (comment?, training*) >
<!ELEMENT training (#PCDATA) >
<!ELEMENT training_types (comment?, training_type*) >
<!ELEMENT training_type (#PCDATA) >
<!ELEMENT comment (#PCDATA) >
<!ELEMENT users (comment?, user*) >
<!ELEMENT user (#PCDATA) >
<!ELEMENT customfields (comment?, customfield*) >
<!ELEMENT customfield (#PCDATA) >
<!ELEMENT configuration (app.width?, app.height?, app.location.x?, app.location.y?, limit.max?, limit.min?, nbr.visible.months?, app.maximized?, app.lookfeel.on?, app.gradient.on?)>
<!ELEMENT app.width (#PCDATA)>
<!ELEMENT app.height (#PCDATA)>
<!ELEMENT app.location.x (#PCDATA)>
<!ELEMENT app.location.y (#PCDATA)>
<!ELEMENT limit.max (#PCDATA)>
<!ELEMENT limit.min (#PCDATA)>
<!ELEMENT nbr.visible.months (#PCDATA)>
<!ELEMENT app.maximized (#PCDATA)>
<!ELEMENT app.lookfeel.on (#PCDATA)>
<!ELEMENT app.gradient.on (#PCDATA)>

<!ATTLIST training id ID #REQUIRED >
<!ATTLIST training training_type IDREF #REQUIRED >
<!ATTLIST training duration CDATA #IMPLIED >
<!ATTLIST training limits CDATA #REQUIRED >
<!ATTLIST training distance CDATA #IMPLIED >
<!ATTLIST training active (yes | no) #REQUIRED >

<!ATTLIST training_type id ID #REQUIRED >
<!ATTLIST training_type priority CDATA #REQUIRED >
<!ATTLIST training_type intensity CDATA #REQUIRED >
<!ATTLIST training_type time CDATA #REQUIRED >

<!ATTLIST users default IDREF #IMPLIED >
<!ATTLIST user id ID #REQUIRED >
<!ATTLIST user weight CDATA #REQUIRED >
<!ATTLIST user size CDATA #REQUIRED >
<!ATTLIST user year_of_birth CDATA #REQUIRED >
<!ATTLIST user gender (male | female) #REQUIRED >

=== BackupTheBerlios/jpulsemonitor/JPulseMonitor/resources/administration.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE administration SYSTEM "administration.dtd">
<administration>
	<configuration>
		<limit.max>160</limit.max>
		<limit.min>126</limit.min>
		<nbr.visible.months>3</nbr.visible.months>
		<app.maximized>no</app.maximized>
		<app.lookfeel.on>yes</app.lookfeel.on>
		<app.gradient.on>no</app.gradient.on>
	</configuration>

	<training_types>
		<comment>All possible types of training</comment>
		<training_type id="y-1" intensity="&gt;90%HFmax" priority="tief" time="&lt;10 Sek.">Ultrakurzzeitausdauer</training_type>
		<training_type id="y-2" intensity="&gt;90%HFmax" priority="tief" time="10-35 Sek">Schnelligkeitausdauer</training_type>
		<training_type id="y-3" intensity="&gt;90%HFmax" priority="tief" time="35-120 Sek">Kurzzeitausdauer</training_type>
		<training_type id="y-4" intensity="&gt;90%HFmax" priority="tief" time="2-10 Min">Mittelzeitausdauer</training_type>
		<training_type id="y-5" intensity="65-80% HFmax" priority="mittel" time="10-35 Min">Langzeitausdauer 1</training_type>
		<training_type id="y-6" intensity="75-85% HFmax" priority="hoch" time="35-90 Min">Langzeitausdauer 2</training_type>
		<training_type id="y-7" intensity="75-85%HFmax" priority="mittel" time="90-360 Min">Langzeitausdauer 3</training_type>
		<training_type id="y-8" intensity="75-85% HFmax" priority="tief" time="&gt;360 Min">Langzeitausdauer 4</training_type>
		<training_type id="y-9" intensity="65-70% HFmax" priority="mittel" time="~45 Min">Regenerations- und Kompensationstraining</training_type>
		<training_type id="y-10" intensity="&gt;90% HFmax" priority="tief" time="60-90 Min">Wettkampfspezifischen Ausdauer</training_type>
	</training_types>

	<trainings>
		<comment>All possible trainings</comment>
		<training active="yes" distance="8.0" duration="60.0" id="t-1" limits="126/165" training_type="y-6">Laufen (lang)</training>
		<training active="no" distance="4.0" duration="30.0" id="t-2" limits="126/165" training_type="y-5">Laufen (kurz)</training>
		<training active="no" distance="10.0" duration="60.0" id="t-3" limits="124/154" training_type="y-9">Rollerblading (gem체tlich)</training>
		<training active="yes" distance="10.0" duration="45.0" id="t-4" limits="126/165" training_type="y-6">Rollerblading (Madis retour)</training>
		<training active="yes" distance="20.0" duration="45.0" id="t-5" limits="124/154" training_type="y-6">Fahrrad (Rolle)</training>
		<training active="yes" distance="10.0" duration="60.0" id="t-6" limits="126/165" training_type="y-6">Laufen (ganz oben rum)</training>
		<training active="yes" distance="15.0" duration="60.0" id="t-7" limits="124/154" training_type="y-6">Rollerblading (Madis, R체tsch., B.bach)</training>
		<training active="yes" distance="10.0" duration="60.0" id="t-8" limits="126/160" training_type="y-6">Mit Wernly (2-4 Steigerungsl채ufe)</training>
	</trainings>

	<users default="u-1">
		<comment>All users (real persons) of the system</comment>
		<user gender="male" id="u-1" size="1.86" weight="74.0" year_of_birth="1978">Adrian B체rki</user>
	</users>

	<customfields><customfield>Test</customfield></customfields>

</administration>
