=== BackupTheBerlios/jpulsemonitor/JPulseMonitor/resources/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD for exercise -->
<!ELEMENT data (exercises, customfields) >
<!ELEMENT exercises (comment?, exercise*) >
<!ELEMENT exercise (#PCDATA) >
<!ELEMENT customfields (comment?, customfield*)>
<!ELEMENT customfield (#PCDATA) >

<!ATTLIST exercises id ID #REQUIRED >
<!ATTLIST exercise id ID #REQUIRED >
<!ATTLIST exercise date CDATA #REQUIRED >
<!ATTLIST exercise training CDATA #REQUIRED >
<!ATTLIST exercise weight CDATA #IMPLIED>
<!ATTLIST exercise kcal CDATA #IMPLIED >
<!ATTLIST exercise average_hr CDATA #IMPLIED >
<!ATTLIST exercise time_in_zone CDATA #IMPLIED >
<!ATTLIST exercise exercise_time CDATA #REQUIRED >

<!ATTLIST customfield id CDATA #REQUIRED >
<!ATTLIST customfield name CDATA #REQUIRED >

=== BackupTheBerlios/jpulsemonitor/JPulseMonitor/resources/exercises_u-1.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE data SYSTEM "data.dtd">
<data>
	<exercises id="u-1">
		<exercise average_hr="157" date="29-05-2004" exercise_time="55.14" id="e-1" kcal="754" time_in_zone="47.59" training="t-1" weight="74.1">Running (long)</exercise>
		<exercise average_hr="127" date="31-05-2004" exercise_time="40.36" id="e-2" kcal="314" time_in_zone="24.55" training="t-5">Seit langem mal wieder</exercise>
		<exercise average_hr="158" date="06-06-2004" exercise_time="53.34" id="e-3" kcal="734" time_in_zone="48.37" training="t-1">Running (long)</exercise>
		<exercise average_hr="157" date="07-06-2004" exercise_time="54.2" id="e-4" kcal="738" time_in_zone="47.45" training="t-1">Running (long)</exercise>
		<exercise average_hr="160" date="01-07-2004" exercise_time="54.0" id="e-5" kcal="734" time_in_zone="44.0" training="t-1" weight="73.2">Running (long)</exercise>
		<exercise average_hr="159" date="05-07-2004" exercise_time="51.38" id="e-6" kcal="722" time_in_zone="38.59" training="t-1">Abbau Restalkohol...</exercise>
		<exercise average_hr="163" date="06-07-2004" exercise_time="52.4" id="e-7" kcal="766" time_in_zone="31.37" training="t-1" weight="73.5">Kurz nach dem Essen, Puls sehr hoch...</exercise>
		<exercise average_hr="139" date="10-07-2004" exercise_time="46.04" id="e-8" kcal="508" time_in_zone="43.59" training="t-5"/>
		<exercise average_hr="136" date="12-07-2004" exercise_time="47.45" id="e-9" kcal="510" time_in_zone="44.34" training="t-5" weight="73.7"/>
		<exercise average_hr="135" date="14-07-2004" exercise_time="45.44" id="e-10" kcal="462" time_in_zone="41.4" training="t-5" weight="73.7"/>
		<exercise average_hr="153" date="15-07-2004" exercise_time="45.01" id="e-11" kcal="560" time_in_zone="27.54" training="t-4"/>
		<exercise average_hr="159" date="25-07-2004" exercise_time="52.37" id="e-12" kcal="731" time_in_zone="45.56" training="t-1" weight="73.1"/>
		<exercise average_hr="152" date="26-07-2004" exercise_time="55.22" id="e-13" kcal="724" time_in_zone="52.56" training="t-1" weight="72.9">Verzögerung, Fränze angetroffen</exercise>
		<exercise average_hr="154" date="27-07-2004" exercise_time="54.38" id="e-14" kcal="726" time_in_zone="48.55" training="t-1">Verzögerung, Thomi u Dagi angetroffen</exercise>
		<exercise average_hr="151" date="28-07-2004" exercise_time="40.08" id="e-15" kcal="497" time_in_zone="30.14" training="t-4" weight="73.9"/>
		<exercise average_hr="160" date="31-07-2004" exercise_time="53.47" id="e-16" kcal="760" time_in_zone="39.54" training="t-1" weight="73.1"/>
		<exercise average_hr="158" date="02-08-2004" exercise_time="51.4" id="e-17" kcal="716" training="t-1"/>
		<exercise average_hr="150" date="03-08-2004" exercise_time="38.57" id="e-18" kcal="486" time_in_zone="22.45" training="t-4" weight="72.3"/>
		<exercise average_hr="152" date="05-08-2004" exercise_time="52.55" id="e-19" kcal="687" time_in_zone="42.52" training="t-1" weight="72.4"/>
		<exercise average_hr="158" date="09-08-2004" exercise_time="51.25" id="e-20" kcal="701" time_in_zone="41.48" training="t-1" weight="72.8">Meet Thomi again :-)</exercise>
		<exercise average_hr="134" date="12-08-2004" exercise_time="45.31" id="e-21" kcal="478" time_in_zone="44.05" training="t-5"/>
		<exercise average_hr="153" date="14-08-2004" exercise_time="51.01" id="e-22" kcal="674" time_in_zone="27.56" training="t-1"/>
		<exercise average_hr="151" date="23-08-2004" exercise_time="55.45" id="e-23" kcal="711" time_in_zone="34.23" training="t-1">Mit Kusi</exercise>
		<exercise average_hr="132" date="24-08-2004" exercise_time="45.29" id="e-24" kcal="469" training="t-5" weight="74.3"/>
		<exercise average_hr="157" date="28-08-2004" exercise_time="63.11" id="e-25" kcal="851" time_in_zone="35.28" training="t-6" weight="73.8">Das erste mal auf der neuen Tour</exercise>
		<exercise average_hr="130" date="30-08-2004" exercise_time="45.31" id="e-26" kcal="397" time_in_zone="22.35" training="t-5"/>
		<exercise average_hr="163" date="30-08-2004" exercise_time="52.54" id="e-27" kcal="762" training="t-1">Laufen mit Stettler</exercise>
		<exercise average_hr="150" date="31-08-2004" exercise_time="61.35" id="e-28" kcal="777" time_in_zone="14.37" training="t-7">Bladen mit Stettler</exercise>
		<exercise average_hr="148" date="06-09-2004" exercise_time="55.48" id="e-29" kcal="683" time_in_zone="46.1" training="t-1" weight="73.6">Mit Wernly</exercise>
		<exercise average_hr="155" date="09-09-2004" exercise_time="63.32" id="e-30" kcal="839" time_in_zone="42.47" training="t-6" weight="73.3"/>
		<exercise average_hr="145" date="12-09-2004" exercise_time="53.13" id="e-31" kcal="629" time_in_zone="45.31" training="t-1"/>
		<exercise average_hr="155" date="13-09-2004" exercise_time="66.15" id="e-32" kcal="150" time_in_zone="52.04" training="t-6">Mit Ulei und Wernly</exercise>
		<exercise average_hr="156" date="19-09-2004" exercise_time="53.21" id="e-33" kcal="708" time_in_zone="40.45" training="t-1">Neue Runde via. Hirschpark</exercise>
		<exercise average_hr="152" date="21-09-2004" exercise_time="54.08" id="e-34" kcal="690" time_in_zone="33.14" training="t-1" weight="73.6"/>
	<exercise average_hr="155" date="27-09-2004" exercise_time="48.41" id="e-35" kcal="638" time_in_zone="40.31" training="t-1"/><exercise average_hr="153" date="28-09-2004" exercise_time="55.05" id="e-36" kcal="717" time_in_zone="43.32" training="t-1"/><exercise average_hr="158" date="29-09-2004" exercise_time="50.34" id="e-37" kcal="689" time_in_zone="45.03" training="t-1"/><exercise average_hr="152" date="01-10-2004" exercise_time="55.21" id="e-38" kcal="718" time_in_zone="49.47" training="t-1">Mit Ule, Wernly und Beat</exercise><exercise average_hr="157" date="02-10-2004" exercise_time="47.57" id="e-39" kcal="643" time_in_zone="32.57" training="t-1">Mit Role</exercise><exercise average_hr="147" date="04-10-2004" exercise_time="56.16" id="e-40" kcal="676" time_in_zone="45.52" training="t-8" weight="74.3">Richtung Elzmatt</exercise><exercise average_hr="156" date="06-10-2004" exercise_time="47.41" id="e-41" kcal="637" time_in_zone="41.36" training="t-1"/><exercise average_hr="151" date="11-10-2004" exercise_time="55.54" id="e-42" kcal="697" time_in_zone="41.09" training="t-8" weight="74.7">Richtung Windhunderennbahn</exercise><exercise average_hr="157" date="12-10-2004" exercise_time="40.46" id="e-43" kcal="543" time_in_zone="21.01" training="t-1"/><exercise average_hr="158" date="31-10-2004" exercise_time="52.43" id="e-44" kcal="723" time_in_zone="16.41" training="t-1" weight="75.8">Erstes Training nach USA</exercise><exercise average_hr="159" date="04-11-2004" exercise_time="50.01" id="e-45" kcal="686" time_in_zone="41.04" training="t-1"/></exercises>

	<customfields>
		<customfield id="e15" name="polarindex">12345</customfield>
		<customfield id="e16" name="polarindex">54321</customfield>
		<customfield id="e16" name="o2">12</customfield>
	</customfields>
</data>
